from enum import Enum


class EvidenceCategory(str, Enum):
    SOCIAL_ENGINEERING = "SOCIAL_ENGINEERING"
    CREDENTIAL_THEFT = "CREDENTIAL_THEFT"
    FINANCIAL_FRAUD = "FINANCIAL_FRAUD"
    SENSITIVE_INFORMATION_REQUEST = "SENSITIVE_INFORMATION_REQUEST"
    SUSPICIOUS_ATTACHMENT = "SUSPICIOUS_ATTACHMENT"
    SENDER_SPOOFING = "SENDER_SPOOFING"
    SUSPICIOUS_URL = "SUSPICIOUS_URL"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
